# This is a config for E2B sandbox template.
# You can use template ID (1i8iaka95y5tnftas67h) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("1i8iaka95y5tnftas67h") # Sync sandbox
# sandbox = await AsyncSandbox.create("1i8iaka95y5tnftas67h") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('1i8iaka95y5tnftas67h')

team_id = "fa04bbd2-33ad-4e8e-badb-4caa88913ece"
start_cmd = "/compile_backend.sh"
dockerfile = "e2b.Dockerfile"
template_id = "1i8iaka95y5tnftas67h"
